- name: r | add R repository
  shell:
    echo 'deb http://cran.rstudio.com/bin/linux/ubuntu xenial-cran35/' | sudo tee /etc/apt/sources.list.d/cran.list
    creates=/etc/apt/sources.list.d/cran.list
  become: yes

- name: r | fetch R signing key
  command: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  become: yes

- name: r | update apt cache
  apt: update_cache=yes
  become: yes

- name: install required libraries
  apt:
    name:
      - mesa-common-dev
      - libglu1-mesa-dev
      - libgsl0-dev
      - zlib1g-dev
      - libcurl4-openssl-dev
      - libx11-dev
      - xvfb
      - r-base
      - r-base-dev
      - libfreetype6-dev
      - libmagick++-dev
      - libssl-dev
    update_cache: true
  become: true
  become_user: root

- name: start xvfb server
  command: Xvfb :7 -screen 0 1280x1024x24
  async: 45
  poll: 0
  become: yes


- name: check for package upgrades
  command: /usr/bin/Rscript --slave --no-save --no-restore-history -e "update.packages(checkBuilt=TRUE, ask=FALSE, repos='http://cran.cnr.Berkeley.edu', INSTALL_opts = c('--no-lock'))"
  become: yes


- name: install packages
  command: /usr/bin/Rscript --slave --no-save --no-restore-history -e "if (! ('{{ item }}' %in% installed.packages()[,'Package'])) install.packages(pkgs='{{ item }}', repos=c('http://cran.cnr.Berkeley.edu'))"
  become: yes
  with_items:
    - rgl
    - ape
    - geiger
    - nlme
    - codetools
    - devtools
    - diversitree
    - phytools
    - dplyr
  environment:
    DISPLAY: :7


- name: install github packages
  command: /usr/bin/Rscript --slave --no-save --no-restore-history -e "options(repos='http://cran.cnr.Berkeley.edu');library(devtools);install_github('{{item}}')"
  become: yes
  with_items:
    - hafen/cardoonTools
    - tangelo-hub/romanescoTools
    - arborworkflows/aRbor
  environment:
    DISPLAY: :7
